# Generated by Django 2.2.10 on 2021-02-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20210216_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
